apiVersion: batch/v1
kind: Job
metadata:
  name: kubeaudit
spec:
  template:
    metadata:
      labels:
        app: kubeaudit
    spec:
      containers:
      - name: kubeaudit
        image: shopify/kubeaudit:latest
        command: ["kubeaudit"]
        args: ["version"]
      restartPolicy: Never
